// Reads `codex debug models` and derives the per-model windows and accepted
// efforts recorded in lib/codex-model-specs.js. Shared by the sync script and
// the manifest drift test; importing it has no side effects.

import { spawnSync } from 'node:child_process';

function runCodex(args) {
  const options = { encoding: 'utf8', windowsHide: true, timeout: 120_000, maxBuffer: 64 * 1024 * 1024 };
  // On Windows `codex` is an npm .cmd shim that needs a shell. The arguments
  // are constants, so the command line is built whole (an args array with
  // shell:true is deprecated) and nothing user-controlled reaches it.
  return process.platform === 'win32'
    ? spawnSync(['codex', ...args].join(' '), { ...options, shell: true })
    : spawnSync('codex', args, options);
}

export function codexInstalled() {
  const res = runCodex(['--version']);
  return !res.error && res.status === 0;
}

export function readCodexModels() {
  const res = runCodex(['debug', 'models']);
  if (res.error || res.status !== 0) {
    const why = res.error?.message ?? (res.stderr.trim() || `exit ${res.status}`);
    throw new Error(`codex debug models failed: ${why}`);
  }
  return parseCodexModels(res.stdout);
}

const positiveInt = (value) => Number.isSafeInteger(value) && value > 0;

export function parseCodexModels(text) {
  const doc = JSON.parse(text);
  if (!Array.isArray(doc?.models)) throw new Error('codex debug models: no "models" array');
  return doc.models.map((model) => {
    const slug = model?.slug;
    const efforts = model?.supported_reasoning_levels?.map((level) => level?.effort);
    if (typeof slug !== 'string' || !slug) throw new Error('codex debug models: model without slug');
    if (!positiveInt(model.context_window) || !positiveInt(model.max_context_window)) {
      throw new Error(`codex debug models: ${slug} has no valid context_window/max_context_window`);
    }
    if (!efforts?.length || !efforts.every((effort) => typeof effort === 'string' && effort)) {
      throw new Error(`codex debug models: ${slug} has no supported_reasoning_levels`);
    }
    return {
      slug,
      visibility: model.visibility,
      contextWindow: model.context_window,
      maxContextWindow: model.max_context_window,
      efforts,
    };
  });
}

// Spec per manifest model id, in the given order. Throws when Codex does not
// list a model the manifest depends on.
export function buildSpecs(codexModels, ids) {
  const bySlug = new Map(codexModels.map((model) => [model.slug, model]));
  const specs = {};
  for (const id of ids) {
    const model = bySlug.get(id);
    if (!model) throw new Error(`model "${id}" is not listed by codex debug models`);
    specs[id] = {
      contextWindow: model.contextWindow,
      maxContextWindow: model.maxContextWindow,
      efforts: model.efforts,
    };
  }
  return specs;
}

export function renderSpecsModule(specs) {
  const rows = Object.entries(specs).map(([id, { contextWindow, maxContextWindow, efforts }]) =>
    `  '${id}': spec(${contextWindow}, ${maxContextWindow}, [${efforts.map((e) => `'${e}'`).join(', ')}]),`);
  return [
    '// Generated by scripts/sync-codex-models.js from `codex debug models`; do not edit by hand.',
    '// Token windows and accepted reasoning efforts for every model in AllCodexAgents.',
    'const spec = (contextWindow, maxContextWindow, efforts) =>',
    '  Object.freeze({ contextWindow, maxContextWindow, efforts: Object.freeze(efforts) });',
    '',
    'export const CodexModelSpecs = Object.freeze({',
    ...rows,
    '});',
    '',
  ].join('\n');
}

// Agent entries whose effort the model rejects, and accepted efforts that no
// agent entry covers. Alias names are a human decision, so both need a manual
// manifest edit.
export function effortDrift(agents, specs) {
  const unsupported = agents.filter((agent) => !specs[agent.model]?.efforts.includes(agent.effort))
    .map(({ name, model, effort }) => ({ name, model, effort }));
  const uncovered = Object.entries(specs).flatMap(([model, { efforts }]) =>
    efforts.filter((effort) => !agents.some((a) => a.model === model && a.effort === effort))
      .map((effort) => ({ model, effort })));
  return { unsupported, uncovered };
}

// Listed Codex models that the manifest has no agents for (information only).
export function unlistedModels(codexModels, ids) {
  return codexModels.filter((m) => m.visibility === 'list' && !ids.includes(m.slug)).map((m) => m.slug);
}
